# This DML querie is for calculating and updating the different metrics such as DesignPointsPercent, DMPointsPercent, DevPointsPercent, Interest, designtointerest, dmtointerest and devtointerest for new students.
use Coderstrust;
update students
set DesignPointsPercent=
(SELECT Sum(DesignPoints)/75
from DesignQuestions)
where studentID='13239';
update students
set DMPointsPercent=
(SELECT Sum(DMPoints)/75
from DMQuestions)
where StudentID='13239';
update students
set DevPointsPercent=
(SELECT Sum(DPoints)/75
from DevQuestions)
where StudentID='13239';
update students
set Interest=(DesignPointsPercent+DMPointsPercent+DevPointsPercent)
where StudentID='13239';
update students
set designtointerest=DesignPointsPercent/Interest
where StudentID='13239';
update students
set dmtointerest=DMPointsPercent/Interest
where StudentID='13239';
update students
set devtointerest=DevPointsPercent/Interest
where StudentID='13239';
